### ISSUE TITLE
Broken link / typo on DNS documentation

### ISSUE THREAD

**Issue by tehcyx** [gardener/documentation#129]
On the documentation page https://gardener.cloud/documentation/guides/administer_shoots/dns_providers/ the first paragraph has a broken link (bold), as well as a typo (bold)

> Gardener can manage DNS records on your behalf, so that you can request them via different resource types (see **here**) within the shoot cluster. The domains for which you are permitted to request records, are however restricted and depend on the DNS provider **confguration**.

I believe instead of pointing here: https://gardener.cloud/documentation/guides/administer_shoots/dns_names/_index.md#Introduction it should point to https://gardener.cloud/documentation/guides/administer_shoots/dns_names/#Introduction

**Comment by tehcyx** [comment]
CC @timuthy

**Comment by timuthy** [comment]
@g-pavlov apparently the link resolution does not work the way we use it [here](https://github.com/timuthy/documentation/blame/ccbb77d307c3b1402b51b6e0606c4090dd237c15/website/documentation/guides/administer_shoots/dns_providers/_index.md#L15). Do you have more information about how these relative links are supposed to work?

**Comment by g-pavlov** [comment]
I see you figured it out but for the record and for future inquiries, gardener.cloud is is built with a Hugo site configuration for [pretty URLs](https://gohugo.io/content-management/urls/). That is, it creates a folder with the name of the .md file and places an `index.html` with the content inside so that it can result in REST-like URL pattern. So if you have dns_names.md that will be built into `dns_names/index.html` and be available at runtime as `/dns_names`.. pretty, huh? :-) 

The nasty effect is that your relative links are no longer natural, so from the content perspective you always need to go one level up and when you reference another document, you need to consider only its name, without the extension, so that at runtime that would resolve to the index.html with the actual document content inside.
