### ISSUE TITLE
Link to the CCLA PDF file is broken

### ISSUE THREAD

**Issue by berendt** [gardener/documentation#143]
The linked PDF file in the "Corporate Contributor License Agreement" section (``/doc/cla/SAP%20Corporate%20Contributor%20License%20Agreement%20(5-26-15).pdf``) in the file ``website/documentation/contribute/_index.md`` (published at https://gardener.cloud/documentation/contribute/) does not exist.

The file is available at https://github.com/cla-assistant/cla-assistant/blob/master/SAP%20Corporate%20Contributor%20License%20Agreement%20(5-26-15).pdf.

**Comment by berendt** [comment]
Looks like this link should not be available at all (https://github.com/gardener/documentation/commit/4ebe50ab6113992b64acf809bfcd3065a604cfb2).

Documentation must be synced with CONTRIBUTING.md.

**Comment by g-pavlov** [comment]
Thanks for pointing out. We are currently changing the automation machinery behind the website and release of documentation and temporarily disabled the inclusion of this particular file until a problem with interpreting a certain kind of links on it was fixed. Unfortunately, this coincided with the rare case of a change in the document, which resulted in having a stale version in the docs. 
In the mean time, the problem was solved and we can now include the document again in the documentation bundle, so very soon there should be an up-to-date version available in the docs.

**Comment by g-pavlov** [comment]
This has been fixed
