### ISSUE TITLE
Manually Adding a Node to an Existing Cluster

### ISSUE THREAD

**Issue by databus23** [gardener/documentation#481]
Documentation issue at https://gardener.cloud/blog/2019/06.11-manually-adding-a-node-to-an-existing-cluster/

The tutorial promised in this article is nowhere to be found.

**Comment by n-boshnakov** [comment]
Thank you for the heads-up. This blog post used to refer to an [outdated guide which has since been removed](https://github.com/gardener/documentation/commit/10d214512ce857a646d3bc575e1e89460baf503b#diff-5c72e1a8415a05f5946ab47b7a6586b54df9af1a93e95f982c5ea5f0994d0444).

I will be removing the guide as it provides no benefit.
