### ISSUE TITLE
Add PR review policies

### ISSUE THREAD

**Issue by zanetworker** [gardener/documentation#92]
**What would you like to be added**:
In our PR checklist we don't yet have a review policy, we should add one that includes: 

-  PR review response time and `Request Changes` enforcement.
- ....

**Comment by stoyanr** [comment]
## Meeting Minutes 10.06.2020:

**Initial agenda:**

* How could we make Gardener code reviews happen faster and distribute them better.
* Would it make sense to introduce Gardener-specific coding guidelines, what these may contain, and how could we create them (not discussed).
* How could we ensure that when a reviewer requests changes he follows up, as otherwise this leads to big delays (proposed by Adel).

**Summary of outcomes:**

* Higher effort to rebase / keep-up that negatively affects developer productivity should be balanced with better quality of the code when more people are reviewing.
* **"Primary" reviewers *should* review within 2 weeks**, while "optional" *can* review. Primary reviewers are defined by GitHub teams.
* **We should try to keep PRs small enough** to make reviews easier / less intimidating. We should raise the awareness about this, however we were not able to identify an objective measure for PR size.
* **When introducing a feature, we should avoid refactoring existing code**, to keep the PR smaller and self-contained (and vice versa).
* **PR author should `/assign` the right person** / people to the PR and actively drive the PR reviews so that the process completes as fast as possible.
* The bot could assign a concrete team based on /area labels (?, proposed but no final agreement).
* For many PRs, we need an opinion from a "domain expert" in addition to an approval from an "approver" (?, no final agreement how to achieve this).
* We could make reviews part of daily syncs to organise ourselves who should review what (?, proposed but most participants sceptical).
* **Everybody should go through PRs at least once per day** and invest at least 30 minutes (preferably more) in reviews. However, we were so far not able to identify ways to raise the likelihood of this happening.
* **We should follow consistently a promotion process from "reviewer" to "approver"**, similar to the one in the Kubernetes community, based on the demonstrated experience of reviewers, number of reviews, etc. So far such a process is not formalised.
* **We should raise the awareness that if a reviewer requests changes he or she should also follow-up within max 2 days** of the requested changes being introduced. After 2 days of non-action, such reviews should be dismissed to enable merging. The author is still responsible to make sure that the reviewer is aware about this changes.
* **Efforts to make integration testing easier should be ramped up** as this has the potential to reduce the effort to manually test the PR by the reviewer.

**Comment by g-pavlov** [comment]
> We could make reviews part of daily syncs to organize ourselves who should review what (?, proposed but most participants sceptical).

The proposal was slightly different and perhaps not well understood - to regularly (once a week for example) review the status of the PRs in review and to surface and address potential issues with compliance with the PR review process that we define (not the PRs topics themselves). 

In essence, it's about filtering PRs that have no reviewer or have been in limbo for too long after review was requested. The event can be used then to assign and re-assign PRs for reviews to keep their pulse beating and improve the load distribution and make it more transparent. I've observed a similar practice in k8s SIGs and it takes about 10-15 minutes on their bi-weekly meetings. 

All things considered, it's a zero-investment practice that we can employ today and it can help until we come up with tool-assisted approaches. Such practice will build up the culture of consciousnesses, without which no tools or process will work.

Technically:
- The exact interval for such reviews would depend on what we define as PR review "sla" and how are we doing with it: once a week, bi-weekly, monthly. It doesn't have to be daily for sure and will get occasional over the time, once the right culture is in place.
- The tool support may obsolete the need for this, introducing automatic and/or assisted review assignments and nudging and re-assignments after a PR timeframe for review expires. But I see the tool support working to sustain the community culture that has already to be there in the first place.

**Comment by g-pavlov** [comment]
To be clear - this issue is in the documentation repo because at the end we are going to formalize the decisions into a guide in the section that describes our processes.
But the discussion is about the whole Gardener project, not the documentation.

**Comment by zanetworker** [comment]
@stoyanr thanks for following up. I guess now we should try to find a place to put it into a review guide. 

@g-pavlov do you think it makes sense to add the guide to this repo?

**Comment by g-pavlov** [comment]
It's the contract between maintainers and contributors, so I guess it's logical to have it somewhere here: https://gardener.cloud/contribute/code

**Comment by vlerenc** [comment]
I was not really sure how to interpret the can/may/should/proposed when I read them a week ago, but when @rfranzke asked me about these meeting minutes today, we chatted and here a proposal what could be done.

It would be great, if you could review and then of course help with the implementation, if we are going to leverage the robot for that.

And here we go with the "soft" proposals:
- [ ] Write a pull request guideline (take the points from https://github.com/gardener/documentation/issues/92#issuecomment-642481752), publish it, and refer to it from within the (default) PR template that a PR author has to confirm having read and respected
- [ ] Write a pull request review guideline (take the points from https://github.com/gardener/documentation/issues/92#issuecomment-642481752) and publish it alongside the pull request guideline
- [ ] Amend both with general advice:
  - [ ] GitHub queries for bookmarking for:
    - [ ] Issues/PRs user is assigned to
    - [ ] Issues/PRs user is invited as reviewer to
    - [ ] Issues/PRs user is author of
  - [ ] Guideline how to improve effeciency with GitHub notifications and Outlook (and other e-mail clients), so that people do not turn off notifications or send them straight to the trash bin, e.g.:
    - [ ] Use Outlook rules to group issues and pull requests in separate folders, possibly even by repository
    - [ ] Exclude notification e-mails that directly mention the user, so that these remain in the inbox
    - [ ] Use the conversations feature in Outlook, so that updates on the same issue/PR stay together

And here the list with the "hard" proposals:
- [ ] APIBot that automatically adds `kind/api-change` and `needs/second-opinion` to PRs if sources are changed in the `pkg/apis` folder (or similar API paths configured by regex) and removes it again if no longer changed
- [ ] SizeBot that automatically sets appropriate `size/*` label to PRs based on added/removed LoC and complains about `size/l` and especially `size/xl` PRs that automatically require `needs/second-opinion` (exclude the `vendor` folder as this would always trigger `size/xl`, but that’s actually not true/misleading; or similar to-be-ignored paths configured by regex)
- [ ] RebaseBot that automatically adds `needs/rebase` label to PRs if there are merge conflicts and removes it again if resolved
- [ ] ReviewBot
  - [ ] Automatically add `needs/review` for new PRs (and until `needs/lgtm` or `reviewed/lgtm` is set)
  - [ ] Automatically invite people based on labels (see reviewers in https://github.tools.sap/kubernetes/kube-docs/wiki/GitHub-Labels); possibly later also folders if useful/applicable and the code owner files are properly maintained
  - [ ] Automatically set `needs/changes` if someone submits a review with state `CHANGES_REQUESTED` and remove it again if there is no more review in that state
  - [ ] Automatically set `needs/lgtm` if (and remove it if not):
      - [ ] One reviewer of each label with reviewers has reviewed the PR with state `APPROVED`
      - [ ] ...there are NO other open reviews or reviews in other states than `APPROVED`
  - [ ] Automatically set `reviewed/lgtm` if:
    - [ ] Case 1 without `needs/second-opinion`:
      - [ ] There is at least one review by a code owners with state `APPROVED` AND
      - [ ] ...the `needs/second-opinion` label is NOT set AND
      - [ ] ...the PR is otherwise reviewed, i.e. the `needs/lgtm` label is set
    - [ ] Case 2 with `needs/second-opinion`:
      - [ ] There are at least two reviews by two code owners with state `APPROVED` AND
      - [ ] ...the `needs/second-opinion` label is set AND
      - [ ] ...the PR is otherwise reviewed, i.e. the `needs/lgtm` label is set
  - Only consider reviews with state `APPROVED` newer than the latest commit; older reviews are considered as open/not/never done
  - Help with active notifications to foster better review compliance (time frames consider the weekends, i.e. the next day after Friday is Monday for our common cultural background):
    - [ ] If there are open comments or reviews with state `CHANGES_REQUESTED`, notify the author every 1d
    - [ ] If there are open review invitations, notify the invitee every 1d
    - [ ] Turn PR stale after 1w and rotten after 2w of author inactivity
    - [ ] Invitee inactivity doesn’t stale/rot a PR; however, PR reviews with COMMENTS or CHANGES_REQUESTED that were not updated after a new commit for 1w will be DISMISSED automatically
    - [ ] Automatically close (an issue or) PR after another period of inactivity (60d for issues and 1w for PRs), i.e. issues are auto-closed after 180d and PRs after 3w
  - [ ] Visualize/create review process transparency by either updating a "standing comment" (right after the PR description) or as PR status check (cleaner) with the current review status (what's needed, whose reviews are completed or still open, whether the author has comments to work on and how many, etc.)

WDYT?

P.S.: You can edit this text in https://github.tools.sap/kubernetes/gardener-robot/blob/master/tasks.md

**Comment by zanetworker** [comment]
>  Write a pull request review guideline (take the points from #92 (comment)) and publish it alongside the pull request guideline
Why would the author of a PR read the review guideline, or did I mis-understand the first point? 

>  Guideline how to improve effeciency with GitHub notifications and Outlook (and other e-mail clients), so that people do not turn off notifications or send them straight to the trash bin, e.g.:
too much imperative IMO. 

regarding the Bots proposals, as long as they require no additional actions from the reviewer (they do their things without adding the overhead of knowing about / learning about each), it LGTM :)

**Comment by vlerenc** [comment]
> Why would the author of a PR read the review guideline, or did I mis-understand the first point?

The author would read the PR guide, e.g. whether the correct labels are set, that the PR tries to do only one thing, `size/l` and larger are, when possible, avoided, etc. See points above from your meeting minutes.

The reviewer would read the reviewer guide about responding timely, etc. See points above from your meeting minutes.

> too imperative IMO.

That is just a recommendation, soft in nature, take it if it helps, but make reviewers aware that switching off notifications is not a good idea and if they feel overhelmed, here is some idea how to improve the situation for yourself.

**Comment by vlerenc** [comment]
Hmm... no other feedback @stoyanr @g-pavlov @rfranzke @zanetworker @gardener/gardener-maintainers on https://github.com/gardener/documentation/issues/92#issuecomment-646072329? Does that make sense, no sense, do you want to have another meeting?

**Comment by zanetworker** [comment]
sure, I think we could start simple considering your comments
> The author would read the PR guide, e.g. whether the correct labels are set, that the PR tries to do only one thing, size/l and larger are, when possible, avoided, etc. See points above from your meeting minutes. 

I like this "The active conformance is driven by the bots" whenever possible. Maybe something like: https://github.com/google/triage-party or so.  

So my proposal to move this forward, is whenver it makes sense lets edit and build on [this](https://github.com/gardener/documentation/issues/92#issuecomment-642481752), and file a PR.

**Comment by vlerenc** [comment]
Sure @zanetworker. If you prefer to continue the discussion in the doc, please copy https://github.com/gardener/documentation/issues/92#issuecomment-646072329 over. It was actually meant as a very concrete list of things that could help in this context and was a plan to execute if approved.

**Comment by zanetworker** [comment]
the doc is for the final PR, the discussion about what should be in the Doc or extra points should be tracked here. Similar to Kubernetes. 

That said I don't have any pereference and I saw that things are not moving forward so I propsed the docs for faster formulation of the document itself (similar to proposals and Keps in Kubernetes before they reach final form)

**Comment by zanetworker** [comment]
regarding your list, no objections from my side :)

**Comment by vlerenc** [comment]
Moved to https://github.wdf.sap.corp/kubernetes/kube-backlog/issues/36.

**Comment by n-boshnakov** [comment]
Due to the issue being moved to a [different repo](https://github.wdf.sap.corp/kubernetes/kube-backlog/issues/36), I will be closing it. Any comments regarding this issue should be made in the new repository.

**Comment by n-boshnakov** [comment]
Due to the issue being moved to a [different repo](https://github.wdf.sap.corp/kubernetes/kube-backlog/issues/36), I will be closing it. Any comments regarding this issue should be made in the new repository.
